version: "3.5"

services:
  bibcnrs-front-dev-server:
    image: node:18-alpine
    environment:
      NODE_ENV: development
      VITE_ENV: development
      VITE_BIBAPI_HOST: http://localhost:3000
      VITE_SOURCE_MAP: true
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    networks:
      - bib-frontend-network

networks:
  bib-frontend-network:
    external: true
