version: "3.5"

services:
  bibcnrs-front:
    container_name: bibcnrs-front
    build:
      context: .
      args:
        VITE_BIBAPI_HOST: ${BIBAPI_HOST}
    ports:
      - "8081:8080"
    networks:
      bibfrontend :

networks:
  bibfrontend:
    driver: bridge
    name: bibfrontend
