version: "3.5"

services:
  bibcnrs-front:
    container_name: bibcnrs-front
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/front:${BIBFRONT_VERSION}
    build:
      context: .
      args:
        BIBAPI_HOST: ${BIBAPI_HOST}
        SOURCE_MAP: ${SOURCE_MAP}
    ports:
      - "8080:8080"
    networks:
      bib-frontend-network:

networks:
  bib-frontend-network:
    external: true
