version: "3.5"

services:
  bibcnrs-front:
    image: vxnexus-registry.intra.inist.fr:8083/bibcnrs/bibcnrs-front:${BIBFRONT_VERSION}
    container_name: bibcnrs-front
    ports:
      - "8080:8080"
    networks:
      bibfrontend :

networks:
  bibfrontend:
    driver: bridge
    name: bibfrontend
