version: "3.5"

services:
  bibcnrs-front:
    container_name: bibcnrs-front
    build:
      context: .
    ports:
      - "4200:4200"
    networks:
      bibfrontend :

networks:
  bibfrontend:
    driver: bridge
    name: bibfrontend